### ISSUE TITLE
Retry request logic can cause seg fault

### ISSUE THREAD

**Issue by chrischris292** [preichenberger/go-gdax#69]
### Description
The go-gdax client doesn't check for error before checking status code...`res` can be nil

### Stack trace below:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x131a2be]

goroutine 54 [running]:
github.com/preichenberger/go-gdax.(*Client).Request(0xc4203920f0, 0x144c038, 0x3, 0xc4204dd520, 0x17, 0x0, 0x0, 0x13a15c0, 0xc4200cbc80, 0xc4202be000, ...)
	/Users/christopherchan/code/gocode/src/github.com/preichenberger/go-gdax/client.go:45 +0x13e
github.com/preichenberger/go-gdax.(*Client).GetStats(0xc4203920f0, 0x144cd15, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/christopherchan/code/gocode/src/github.com/preichenberger/go-gdax/product.go:223 +0x14b
github.com/chrischris292/trading/features/feature_impls.(*HistoricalDataStore).run(0xc420442000)
	/Users/christopherchan/code/gocode/src/github.com/chrischris292/trading/features/feature_impls/historical_data_store.go:38 +0x10a
created by github.com/chrischris292/trading/features/feature_impls.NewHistoricalDataStore
	/Users/christopherchan/code/gocode/src/github.com/chrischris292/trading/features/feature_impls/historical_data_store.go:32 +0x17f
exit status 2
```

**Comment by chrischris292** [comment]
sorry, realized this is fixed already in master.
